---
wind-factor: 1.5
wind-direction: (1,0)
wind-speed: 0
burn-duration:
  chaparral: 5
  dense_forest: 30
  canyon: 0.5
  town: 3
ignition-probability:
  chaparral: 0.7
  dense_forest: 0.2
  canyon: 0.9
  town: 0.7
terrain-min-neighbours:
  chaparral: 1
  dense_forest: 2
  canyon: 1
  town: 1
grid: default
# Possible values: default, ignition, powerplant, connected, enclosed, foresttown, forestthick, water
